export default `## nginx configuration generated by libtoserve

server {
  listen  80;
  server_name {{hostName}};

  root "{{location}}";

  index index.php;

  location / {
    try_files $uri @rewrite;
  }

  location ~ (^/favicon\.ico$|^/robots\.txt$) {
    access_log off;
    allow all;
    log_not_found off;
  }

  location ^~ /vendor/ {
    deny all;
    return 404;
  }

  location ~ ^/(install|rebuild|authorize)\.php$ {
    rewrite ^/(.*)$ /core$uri last;
  }

  location ~ ^/update\.php/.*$ {
    rewrite ^ /update.php;
  }

  location @rewrite {
    rewrite ^ /index.php;
  }

  location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
    try_files $uri @rewrite;
    expires max;
    log_not_found off;
  }

  location ~ ^/sites/.*/files/styles/ {
    try_files $uri @rewrite;
  }

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_pass  127.0.0.1:9000;
    fastcgi_read_timeout 2400;
    fastcgi_param PATH_INFO       $fastcgi_path_info;
    fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;
    fastcgi_index index.php;
  }
}`