export default `## nginx configuration generated by libtoserve

server {
  listen  80;
  server_name {{hostName}};

  root "{{location}}";

  index index.php index.html index.htm;

  location / {
    try_files $uri $uri/ =404;
  }

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_pass  127.0.0.1:{{phpfpmPort}};
    fastcgi_read_timeout 2400;
    fastcgi_param PATH_INFO       $fastcgi_path_info;
    fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;
    fastcgi_index index.php;
  }
}`